#############################################################################
# Generated by PAGE version 7.6b
#  in conjunction with Tcl version 8.6
#  Aug 13, 2022 07:44:14 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 899x769+484+263
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnExit \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Exit 
    vTcl:DefineAlias "$top.but46" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab48 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Tk Widgets} -background $vTcl(actual_gui_bg) -height 305 \
        -highlightcolor black -width 700 
    vTcl:DefineAlias "$top.lab48" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    checkbutton $site_3_0.che49 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -relief groove \
        -selectcolor #d9d9d9 -text Check -variable che49 
    vTcl:DefineAlias "$site_3_0.che49" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent50 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 166 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Checkbutton 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Entry Widget} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_3_0.lis53 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -height 4 -highlightcolor black -selectbackground #c4c4c4 \
        -selectforeground black -width 10 
    $site_3_0.lis53 configure -font "TkFixedFont"
    $site_3_0.lis53 insert end text
    vTcl:DefineAlias "$site_3_0.lis53" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes54 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 1 \
        -pady 1 -relief sunken -text Message -width 122 
    vTcl:DefineAlias "$site_3_0.mes54" "Message1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad55 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -relief groove \
        -selectcolor #d9d9d9 -text Radio -variable selectedButton 
    vTcl:DefineAlias "$site_3_0.rad55" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Radiobutton 
    vTcl:DefineAlias "$site_3_0.lab56" "Label3" vTcl:WidgetProc "Toplevel1" 1
    scale $site_3_0.sca57 \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightcolor black -length 100 -resolution 1.0 -tickinterval 0.0 \
        -to 100.0 -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_3_0.sca57" "Scale1" vTcl:WidgetProc "Toplevel1" 1
    scale $site_3_0.sca58 \
        -activebackground $vTcl(analog_color_m) \
        -background $vTcl(actual_gui_bg) -bigincrement 0.0 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -from 0.0 \
        -highlightcolor black -length 100 -orient horizontal -resolution 1.0 \
        -tickinterval 0.0 -to 100.0 -troughcolor #d9d9d9 
    vTcl:DefineAlias "$site_3_0.sca58" "Scale2" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi59 \
        -activebackground #f9f9f9 -background white -font TkDefaultFont \
        -foreground black -from 1.0 -highlightbackground black \
        -highlightcolor black -increment 1.0 -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -to 100.0 
    vTcl:DefineAlias "$site_3_0.spi59" "Spinbox1" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex60 \
        -background white -font TkTextFont -foreground black -height 74 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 166 \
        -wrap word 
    $site_3_0.tex60 configure -font "TkTextFont"
    $site_3_0.tex60 insert end text
    vTcl:DefineAlias "$site_3_0.tex60" "Text1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra61 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 105 
    vTcl:DefineAlias "$site_3_0.fra61" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Frame Widget} 
    vTcl:DefineAlias "$site_3_0.lab62" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Spinbox 
    vTcl:DefineAlias "$site_3_0.lab63" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text HScale 
    vTcl:DefineAlias "$site_3_0.lab64" "Label6" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text VScale 
    vTcl:DefineAlias "$site_3_0.lab65" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Text Widget} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label8" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.che49 \
        -in $site_3_0 -x 40 -y 50 -width 167 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 230 -y 50 -width 166 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 50 -y 20 -width 139 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 230 -y 20 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis53 \
        -in $site_3_0 -x 440 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.mes54 \
        -in $site_3_0 -x 550 -y 50 -width 122 -relwidth 0 -height 61 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad55 \
        -in $site_3_0 -x 40 -y 123 -width 168 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 40 -y 100 -width 129 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.sca57 \
        -in $site_3_0 -x 240 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.sca58 \
        -in $site_3_0 -x 300 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.spi59 \
        -in $site_3_0 -x 440 -y 180 -width 88 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex60 \
        -in $site_3_0 -x 30 -y 190 -width 166 -relwidth 0 -height 74 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra61 \
        -in $site_3_0 -x 570 -y 170 -width 105 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 575 -y 140 -width 99 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 440 -y 150 -width 79 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 310 -y 150 -width 79 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 250 -y 100 -width 69 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 40 -y 164 -width 119 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $top.tLa46 \
        -text Tlabelframe -width 700 -height 375 
    vTcl:DefineAlias "$top.tLa46" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa46
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_3_0.tBu47 \
        -takefocus {} -text Tbutton -compound left 
    vTcl:DefineAlias "$site_3_0.tBu47" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_3_0.tCh48 \
        -variable tch48 -takefocus {} -text Tcheck -compound left 
    vTcl:DefineAlias "$site_3_0.tCh48" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $site_3_0.tCo49 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo49" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_3_0.tEn50 \
        -font TkTextFont -foreground {} -background {} -takefocus {} \
        -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn50" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa51 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text TCombobox -compound left 
    vTcl:DefineAlias "$site_3_0.tLa51" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa52 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {TEntry Widget} -compound left 
    vTcl:DefineAlias "$site_3_0.tLa52" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_3_0.tFr53 \
        -borderwidth 2 -relief groove -width 125 -height 75 
    vTcl:DefineAlias "$site_3_0.tFr53" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_3_0.tLa54 \
        -text Tlabelframe -width 150 -height 75 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $site_3_0.tPr55 \
        -length 100 
    vTcl:DefineAlias "$site_3_0.tPr55" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa56 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text TProgressbar -compound left 
    vTcl:DefineAlias "$site_3_0.tLa56" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale $site_3_0.tSc57 \
        -orient vertical -length 100 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tSc57" "TScale1" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale $site_3_0.tSc58 \
        -length 100 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tSc58" "TScale2" vTcl:WidgetProc "Toplevel1" 1
    ttk::spinbox $site_3_0.tSp59 \
        -from 1 -to 100 -font TkTextFont -foreground {} -background white \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tSp59" "TSpinbox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook $site_3_0.tNo60 \
        -width 212 -height 136 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo60" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.tNo60.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo60.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo60 add $site_3_0.tNo60.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo60.t0
    frame $site_3_0.tNo60.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo60.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo60 add $site_3_0.tNo60.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo60.t1
    frame $site_3_0.tNo60.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo60.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo60 add $site_3_0.tNo60.t2 \
        -padding 0 -sticky nsew -state normal -text {Page 3} -image {} \
        -compound left -underline -1 
    set site_5_2  $site_3_0.tNo60.t2
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.tCh48 \
        -in $site_3_0 -x 130 -y 50 -width 144 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo49 \
        -in $site_3_0 -x 340 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.tEn50 \
        -in $site_3_0 -x 10 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 340 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 20 -y 90 -width 122 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tFr53 \
        -in $site_3_0 -x 200 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 340 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.tPr55 \
        -in $site_3_0 -x 10 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 10 -y 190 -width 102 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSc57 \
        -in $site_3_0 -x 140 -y 230 -anchor nw -bordermode ignore 
    place $site_3_0.tSc58 \
        -in $site_3_0 -x 180 -y 260 -anchor nw -bordermode ignore 
    place $site_3_0.tSp59 \
        -in $site_3_0 -x 310 -y 260 -width 95 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tNo60 \
        -in $site_3_0 -x 450 -y 210 -width 212 -relwidth 0 -height 136 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::combobox $top.tCo47 \
        -font TkTextFont -textvariable combobox1 -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo47" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activeforeground #000000 -anchor w -background $vTcl(actual_gui_bg) \
        -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -text {Available Color Sets:} 
    vTcl:DefineAlias "$top.lab49" "Label9" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 740 -y 20 -width 113 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 150 -y 60 -width 700 -relwidth 0 -height 305 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 150 -y 370 -width 700 -relwidth 0 -height 375 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo47 \
        -in $top -x 270 -y 20 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 80 -y 20 -width 179 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

