#############################################################################
# Generated by PAGE version 7.6b
#  in conjunction with Tcl version 8.6
#  Aug 16, 2022 04:25:43 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    application_exit_png "./Assets/application-exit.png" 
    help_contents32_png "./Assets/help-contents32.png" 
    information_png "./Assets/information.png" 
    document_save_png "./Assets/document-save.png" 
    document_open_png "./Assets/document-open.png" 
    notebook_png "./Assets/notebook.png" 
    internet_png "./Assets/internet.png" 
    applications_system_png "./Assets/applications-system.png" 
    edit_find_png "./Assets/edit-find.png" 
    insert_text_png "./Assets/insert-text.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1160x729+699+309
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "ColorSet Creator Ver 0.1.2"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook $top.tNo47 \
        -width 1148 -height 576 -takefocus {} 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo47.t5 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t5" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t5 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo47.t5
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_4_0.tLa46 \
        -text {Background Colors} -width 380 -height 365 
    vTcl:DefineAlias "$site_4_0.tLa46" "TLabelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.tLa46
    ttk::label $site_5_0.tLa53 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Selected Background Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa53" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_5_0.tEn54 \
        -font TkTextFont -textvariable TEntry1Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn54" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The background color of the tab (widget) you are currently on}
    }
    button $site_5_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_bgColor(1)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but55" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_bgColor(2)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but56" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_bgColor(3)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but57" "Button3" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_5_0.tEn59 \
        -font TkTextFont -textvariable TEntry2Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn59" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn59 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The background of the tab (widget) the mouse is hovering over}
    }
    ttk::entry $site_5_0.tEn60 \
        -font TkTextFont -textvariable TEntry3Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn60" "TEntry3" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn60 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The background of all other tabs (widgets)}
    }
    ttk::label $site_5_0.tLa61 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Active Background Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa61" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa62 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text { InActive Background Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa62" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa53 \
        -in $site_5_0 -x 4 -y 50 -width 190 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn54 \
        -in $site_5_0 -x 196 -y 50 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but55 \
        -in $site_5_0 -x 310 -y 50 -width 33 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but56 \
        -in $site_5_0 -x 312 -y 85 -width 33 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but57 \
        -in $site_5_0 -x 312 -y 120 -width 33 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tEn59 \
        -in $site_5_0 -x 196 -y 85 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn60 \
        -in $site_5_0 -x 196 -y 120 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa61 \
        -in $site_5_0 -x 4 -y 85 -width 190 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa62 \
        -in $site_5_0 -x 4 -y 120 -width 190 -relwidth 0 -anchor nw \
        -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_4_0.tLa47 \
        -text {Foreground Colors} -width 340 -height 365 
    vTcl:DefineAlias "$site_4_0.tLa47" "TLabelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.tLa47
    ttk::label $site_5_0.tLa63 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Selected Foreground Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa63" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa64 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {Active Foreground Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa64" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa65 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor e -justify left \
        -text {InActive Foreground Color:} -compound left 
    vTcl:DefineAlias "$site_5_0.tLa65" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry $site_5_0.tEn66 \
        -font TkTextFont -textvariable TEntry4Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn66" "TEntry4" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn66 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The Text color of the tab (widget) you are currently on}
    }
    ttk::entry $site_5_0.tEn67 \
        -font TkTextFont -textvariable TEntry5Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn67" "TEntry5" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The Text color of the tab (widget) the mouse is hovering over}
    }
    ttk::entry $site_5_0.tEn68 \
        -font TkTextFont -textvariable TEntry6Data -foreground {} \
        -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_5_0.tEn68" "TEntry6" vTcl:WidgetProc "Toplevel1" 1
    bind $site_5_0.tEn68 <<SetBalloon>> {
        set ::vTcl::balloon::%W {The text color of all the other tabs (widgets)}
    }
    button $site_5_0.but69 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_fgColor(1)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but69" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but70 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_fgColor(2)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but70" "Button5" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but71 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command {lambda : on_fgColor(3)} -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 1 \
        -text ... 
    vTcl:DefineAlias "$site_5_0.but71" "Button6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -command on_AutoComputeFG \
        -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text {Auto Compute Foregrounds} -variable che47 
    vTcl:DefineAlias "$site_5_0.che47" "chkAutoComputeForeground" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa63 \
        -in $site_5_0 -x 4 -y 50 -width 190 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa64 \
        -in $site_5_0 -x 4 -y 85 -width 190 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa65 \
        -in $site_5_0 -x 4 -y 120 -width 190 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn66 \
        -in $site_5_0 -x 196 -y 50 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn67 \
        -in $site_5_0 -x 196 -y 85 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tEn68 \
        -in $site_5_0 -x 196 -y 120 -width 114 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but69 \
        -in $site_5_0 -x 310 -y 50 -width 33 -relwidth 0 -height 23 \
        -anchor nw -bordermode ignore 
    place $site_5_0.but70 \
        -in $site_5_0 -x 310 -y 85 -width 33 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but71 \
        -in $site_5_0 -x 310 -y 120 -width 33 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.che47 \
        -in $site_5_0 -x 50 -y 20 -width 257 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_4_0.tLa48 \
        -text Samples -width 380 -height 475 
    vTcl:DefineAlias "$site_4_0.tLa48" "TLabelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.tLa48
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu75 \
        -takefocus {} -text Tbutton -compound left 
    vTcl:DefineAlias "$site_5_0.tBu75" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_5_0.tCh76 \
        -variable tch76 -takefocus {} -text Tcheck -compound left 
    vTcl:DefineAlias "$site_5_0.tCh76" "TCheckbutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa77 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left -text Tlabel \
        -compound left 
    vTcl:DefineAlias "$site_5_0.tLa77" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_5_0.tFr78 \
        -borderwidth 2 -relief groove -width 125 -height 75 
    vTcl:DefineAlias "$site_5_0.tFr78" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $site_5_0.tRa79 \
        -variable selectedButton -text TRadio -compound left 
    vTcl:DefineAlias "$site_5_0.tRa79" "TRadiobutton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_5_0.tLa46 \
        -text Tlabelframe -width 150 -height 75 
    vTcl:DefineAlias "$site_5_0.tLa46" "TLabelframe4" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_5_0.tSe49 \
        -orient vertical 
    vTcl:DefineAlias "$site_5_0.tSe49" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab48 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_5_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_5_0.but49" "Button7" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_5_0.che50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -selectcolor #d9d9d9 \
        -text Checkbutton -variable che50 
    vTcl:DefineAlias "$site_5_0.che50" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_5_0.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -selectcolor #d9d9d9 \
        -text Radiobutton -variable selectedButton 
    vTcl:DefineAlias "$site_5_0.rad51" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_5_0.fra52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_5_0.fra52" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab53 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief sunken -text Label 
    vTcl:DefineAlias "$site_5_0.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab47 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text ttk::Widgets 
    vTcl:DefineAlias "$site_5_0.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab49 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Tk::Widgets 
    vTcl:DefineAlias "$site_5_0.lab49" "Label4" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_5_0.lab50 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Labelframe \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$site_5_0.lab50" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tBu75 \
        -in $site_5_0 -x 20 -y 58 -anchor nw -bordermode ignore 
    place $site_5_0.tCh76 \
        -in $site_5_0 -x 20 -y 98 -width 134 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa77 \
        -in $site_5_0 -x 130 -y 58 -width 82 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tFr78 \
        -in $site_5_0 -x 220 -y 48 -anchor nw -bordermode ignore 
    place $site_5_0.tRa79 \
        -in $site_5_0 -x 20 -y 128 -width 134 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa46 \
        -in $site_5_0 -x 160 -y 138 -anchor nw -bordermode ignore 
    place $site_5_0.tSe49 \
        -in $site_5_0 -x 360 -y 58 -height 160 -relheight 0 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab48 \
        -in $site_5_0 -x 30 -y 238 -width 329 -relwidth 0 -height 3 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but49 \
        -in $site_5_0 -x 30 -y 291 -anchor nw -bordermode ignore 
    place $site_5_0.che50 \
        -in $site_5_0 -x 30 -y 331 -width 127 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.rad51 \
        -in $site_5_0 -x 30 -y 360 -width 128 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.fra52 \
        -in $site_5_0 -x 217 -y 291 -width 125 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab53 \
        -in $site_5_0 -x 125 -y 297 -width 69 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab47 \
        -in $site_5_0 -x 120 -y 20 -width 139 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab49 \
        -in $site_5_0 -x 125 -y 256 -width 129 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab50 \
        -in $site_5_0 -x 200 -y 380 -anchor nw -bordermode ignore 
    ttk::combobox $site_4_0.tCo49 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo49" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_4_0.tLa50 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -relief flat -anchor center -justify left -text {Available ColorSets} \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tLa50" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_0.tBu51 \
        -command on_ApplyColors -takefocus {} -text {Apply Colors} \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tBu51" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_4_0.tBu52 \
        -command on_SaveNewColorSet -takefocus {} -text {Save New ColorSet} \
        -compound left 
    vTcl:DefineAlias "$site_4_0.tBu52" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -anchor w -background $vTcl(actual_gui_bg) \
        -command on_chkDisableWidgets -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -selectcolor #d9d9d9 -text {Disable Widgets} -variable che46 
    vTcl:DefineAlias "$site_4_0.che46" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tLa46 \
        -in $site_4_0 -x 5 -y 67 -width 380 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa47 \
        -in $site_4_0 -x 384 -y 67 -width 380 -relwidth 0 -height 365 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa48 \
        -in $site_4_0 -x 763 -y 67 -width 380 -relwidth 0 -height 475 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCo49 \
        -in $site_4_0 -x 790 -y 30 -width 177 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tLa50 \
        -in $site_4_0 -x 790 -y 10 -width 172 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu51 \
        -in $site_4_0 -x 120 -y 450 -width 183 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tBu52 \
        -in $site_4_0 -x 120 -y 490 -width 183 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.che46 \
        -in $site_4_0 -x 980 -y 28 -width 147 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo47.t6 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t6" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t6 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo47.t6
    button $site_4_1.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnReturn \
        -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RETURN TO MAIN TAB} 
    vTcl:DefineAlias "$site_4_1.but58" "btnTab2Return" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_1.but58 \
        -in $site_4_1 -x 466 -y 253 -width 213 -relwidth 0 -height 43 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo47.t7 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t7" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t7 \
        -padding 0 -sticky nsew -state normal -text {Page 3} -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo47.t7
    button $site_4_2.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnReturn \
        -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RETURN TO MAIN TAB} 
    vTcl:DefineAlias "$site_4_2.but59" "btnTab2Return_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_2.but59 \
        -in $site_4_2 -x 466 -y 253 -width 213 -height 43 -anchor nw \
        -bordermode ignore 
    frame $top.tNo47.t3 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t3" "TNotebook1_t4" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t3 \
        -padding 0 -sticky nsew -state normal -text {Page 4} -image {} \
        -compound left -underline -1 
    set site_4_3  $top.tNo47.t3
    button $site_4_3.but60 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnReturn \
        -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RETURN TO MAIN TAB} 
    vTcl:DefineAlias "$site_4_3.but60" "btnTab2Return_1_1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_3.but60 \
        -in $site_4_3 -x 466 -y 253 -width 213 -height 43 -anchor nw \
        -bordermode ignore 
    frame $top.tNo47.t4 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t4" "TNotebook1_t5" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo47 add $top.tNo47.t4 \
        -padding 0 -sticky nsew -state normal -text {Page 5} -image {} \
        -compound left -underline -1 
    set site_4_4  $top.tNo47.t4
    button $site_4_4.but61 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnReturn \
        -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {RETURN TO MAIN TAB} 
    vTcl:DefineAlias "$site_4_4.but61" "btnTab2Return_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TPanedwindow -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TPanedwindow.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TPanedwindow.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::panedwindow $site_4_4.tPa47 \
        -orient horizontal 
    vTcl:DefineAlias "$site_4_4.tPa47" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_4_4.tPa47.p1 \
        -text {Pane 1} -width 75 -height 200 
    vTcl:DefineAlias "$site_4_4.tPa47.p1" "TPanedwindow1_p1" vTcl:WidgetProc "Toplevel1" 1
    set site_6_0 $site_4_4.tPa47.p1
    $site_4_4.tPa47 add $site_4_4.tPa47.p1 
    $site_4_4.tPa47 pane $site_4_4.tPa47.p1 -weight 0
    ttk::style configure TLabelframe.Label -background $vTcl(actual_gui_bg)
    ttk::style configure TLabelframe.Label -foreground $vTcl(actual_gui_fg)
    ttk::style configure TLabelframe.Label -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style configure TLabelframe -background $vTcl(actual_gui_bg)
    ttk::labelframe $site_4_4.tPa47.p2 \
        -text {Pane 2} -width 125 -height 200 
    vTcl:DefineAlias "$site_4_4.tPa47.p2" "TPanedwindow1_p2" vTcl:WidgetProc "Toplevel1" 1
    set site_6_1 $site_4_4.tPa47.p2
    $site_4_4.tPa47 add $site_4_4.tPa47.p2 
    $site_4_4.tPa47 pane $site_4_4.tPa47.p2 -weight 0
$site_6_0 configure -width 75
    ttk::scale $site_4_4.tSc48 \
        -orient vertical -length 100 -takefocus {} 
    vTcl:DefineAlias "$site_4_4.tSc48" "TScale1" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale $site_4_4.tSc49 \
        -length 100 -takefocus {} 
    vTcl:DefineAlias "$site_4_4.tSc49" "TScale2" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $site_4_4.tPr50 \
        -length 100 
    vTcl:DefineAlias "$site_4_4.tPr50" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_4.scr51 \
        -background $vTcl(actual_gui_bg) -height 15 -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_4.scr51" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

        $base.tNo47.t4.scr51.01 configure -columns Col1 -height 4
        $base.tNo47.t4.scr51.01 configure -columns {Col1}
        $base.tNo47.t4.scr51.01 heading #0 -text {Tree}
        $base.tNo47.t4.scr51.01 heading #0 -anchor center
        $base.tNo47.t4.scr51.01 column #0 -width 63
        $base.tNo47.t4.scr51.01 column #0 -minwidth 20
        $base.tNo47.t4.scr51.01 column #0 -stretch 1
        $base.tNo47.t4.scr51.01 column #0 -anchor w
        $base.tNo47.t4.scr51.01 heading Col1 -text {Col1}
        $base.tNo47.t4.scr51.01 heading Col1 -anchor center
        $base.tNo47.t4.scr51.01 column Col1 -width 63
        $base.tNo47.t4.scr51.01 column Col1 -minwidth 20
        $base.tNo47.t4.scr51.01 column Col1 -stretch 1
        $base.tNo47.t4.scr51.01 column Col1 -anchor w
    place $site_4_4.but61 \
        -in $site_4_4 -x 466 -y 253 -width 213 -height 43 -anchor nw \
        -bordermode ignore 
    place $site_4_4.tPa47 \
        -in $site_4_4 -x 80 -y 70 -anchor nw -bordermode ignore 
    place $site_4_4.tSc48 \
        -in $site_4_4 -x 340 -y 70 -anchor nw -bordermode ignore 
    place $site_4_4.tSc49 \
        -in $site_4_4 -x 410 -y 80 -anchor nw -bordermode ignore 
    place $site_4_4.tPr50 \
        -in $site_4_4 -x 70 -y 290 -anchor nw -bordermode ignore 
    place $site_4_4.scr51 \
        -in $site_4_4 -x 680 -y 60 -width 140 -relwidth 0 -height 101 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra49 \
        -borderwidth 2 -relief sunken -background $vTcl(actual_gui_bg) \
        -height 55 -highlightcolor black -width 1148 
    vTcl:DefineAlias "$top.fra49" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra49
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable StatusTime 
    vTcl:DefineAlias "$site_3_0.lab72" "lblStatusTime" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 5 \
        -relief sunken -text Label -textvariable StatusInfo1 
    vTcl:DefineAlias "$site_3_0.lab73" "lblStatusInfo1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 5 \
        -relief sunken -text Label -textvariable StatusInfo2 
    vTcl:DefineAlias "$site_3_0.lab74" "lblStatusInfo2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 1036 -y 3 -width 109 -relwidth 0 -height 49 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 3 -y 3 -width 542 -relwidth 0 -height 49 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 546 -y 3 -width 489 -relwidth 0 -height 49 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 55 -highlightcolor black -width 1155 
    vTcl:DefineAlias "$top.fra46" "frameBtnBar" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnExit \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image application_exit_png -text Exit 
    vTcl:DefineAlias "$site_3_0.but47" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Exit This Application}
    }
    button $site_3_0.but48 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnHelp \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image help_contents32_png -text Button 
    vTcl:DefineAlias "$site_3_0.but48" "btnHelp" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but48 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Help}
    }
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnInfo \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image information_png -text Button 
    vTcl:DefineAlias "$site_3_0.but49" "btnInfo" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Get Information on this Program}
    }
    button $site_3_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnSaveToJSON -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_save_png -text Button 
    vTcl:DefineAlias "$site_3_0.but46" "btnSaveToJSON" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but46 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Save Colorset Information to JSON File}
    }
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnLoadFromJSON -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image document_open_png -state disabled -text Button 
    vTcl:DefineAlias "$site_3_0.but50" "btnLoadFromJSON" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Load Colorset Informatin from JSON File}
    }
    button $site_3_0.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnViewer \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image notebook_png -text Button 
    vTcl:DefineAlias "$site_3_0.but51" "btnViewer" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but51 <<SetBalloon>> {
        set ::vTcl::balloon::%W {View ColorSet Definitions}
    }
    button $site_3_0.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnInternet -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image internet_png -text Button 
    vTcl:DefineAlias "$site_3_0.but52" "btnInternet" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but52 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Open Colorhut.co in Web Browser for Color Scheme Ideas}
    }
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab53" "lblVSep1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab54" "lblVSep2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab55" "lblVSep3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab56" "lblVSep4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab57 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab57" "lblVSep1_1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnConfig \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image applications_system_png -text Button 
    vTcl:DefineAlias "$site_3_0.but53" "btnConfig" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Preferences}
    }
    button $site_3_0.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnGetInfo -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image edit_find_png -text Button 
    vTcl:DefineAlias "$site_3_0.but54" "btnConfig_1" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but54 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Examine ttk Layouts}
    }
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -borderwidth 3 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -relief groove 
    vTcl:DefineAlias "$site_3_0.lab47" "lblVSep1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but55 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_btnExport \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image insert_text_png -text Button 
    vTcl:DefineAlias "$site_3_0.but55" "btnExport" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but55 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Export Colorset(s) To Python File}
    }
    place $site_3_0.but47 \
        -in $site_3_0 -x 1102 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 1029 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 979 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 8 -y 4 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 59 -y 4 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 163 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 303 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 400 -y 1 -width 3 -relwidth 0 -height 53 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 125 -y 1 -width 3 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 247 -y 1 -width 3 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 1089 -y 1 -width 3 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 954 -y 1 -width 3 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 780 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 570 -y 4 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 483 -y 1 -width 3 -height 53 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 423 -y 4 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo47 \
        -in $top -x 5 -y 90 -width 1148 -relwidth 0 -height 576 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra49 \
        -in $top -x 5 -y 670 -width 1148 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 2 -y 0 -width 1156 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top66 {base} {
    global vTcl
    if {$base == ""} {
        set base .top66
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background gray58 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 405x455+1350+368
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Colorset Creator Info"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Info" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 3 \
        -text Author: 
    vTcl:DefineAlias "$top.lab46" "Label1" vTcl:WidgetProc "Info" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label \
        -textvariable AuthorData 
    vTcl:DefineAlias "$top.lab47" "lblAuthor" vTcl:WidgetProc "Info" 1
    set AuthorData {Label}
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 3 \
        -text Version: 
    vTcl:DefineAlias "$top.lab48" "Label2" vTcl:WidgetProc "Info" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text 1.3 \
        -textvariable InfoVersionData 
    vTcl:DefineAlias "$top.lab49" "Label3" vTcl:WidgetProc "Info" 1
    set InfoVersionData {1.3}
    button $top.but50 \
        -activebackground #f9f9f9 -activeforeground black -background gray58 \
        -borderwidth 2 -command on_btnInfoDismiss -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Dismiss 
    vTcl:DefineAlias "$top.but50" "btnInfoDismiss" vTcl:WidgetProc "Info" 1
    message $top.mes51 \
        -anchor nw -background gray58 -borderwidth 2 \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 1 \
        -pady 1 -relief groove -text Message -textvariable InfoAboutData \
        -width 352 
    vTcl:DefineAlias "$top.mes51" "Message1" vTcl:WidgetProc "Info" 1
    set InfoAboutData {Message}
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text About: 
    vTcl:DefineAlias "$top.lab52" "Label4" vTcl:WidgetProc "Info" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 40 -y 30 -width 89 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 140 -y 30 -width 189 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 30 -y 60 -width 99 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 140 -y 60 -width 159 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 136 -y 390 -width 133 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes51 \
        -in $top -x 26 -y 130 -width 352 -relwidth 0 -height 191 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 30 -y 100 -width 68 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top90 {base} {
    global vTcl
    if {$base == ""} {
        set base .top90
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background gray58 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 805x657+858+336
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "ColorSet Viewer"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "CSViewer" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame $top.fra46 \
        -borderwidth 2 -relief sunken -background gray58 -height 585 \
        -highlightcolor black -width 795 
    vTcl:DefineAlias "$top.fra46" "Frame1_1" vTcl:WidgetProc "CSViewer" 1
    set site_3_0 $top.fra46
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr46" "Scrolledtext1" vTcl:WidgetProc "CSViewer" 1

    $site_3_0.scr46.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap word
    place $site_3_0.scr46 \
        -in $site_3_0 -x 4 -y 4 -width 790 -relwidth 0 -height 575 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_btnViewerDismiss -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Dismiss 
    vTcl:DefineAlias "$top.but47" "btnViewerDismiss" vTcl:WidgetProc "CSViewer" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 3 -y 68 -width 798 -relwidth 0 -height 585 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 660 -y 17 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top92 {base} {
    global vTcl
    if {$base == ""} {
        set base .top92
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background gray58 -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 967x735+824+295
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2545 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "ColorSet Creator Configuration"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "CSConfig" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_ConfigBtnDismiss -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Dismiss 
    vTcl:DefineAlias "$top.but51" "btnDismiss" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook $top.tNo47 \
        -width 942 -height 606 -takefocus {} 
    vTcl:DefineAlias "$top.tNo47" "TNotebook1" vTcl:WidgetProc "CSConfig" 1
    frame $top.tNo47.t0 \
        -borderwidth 2 -relief sunken -background gray53 \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t0" "TNotebook1_t1" vTcl:WidgetProc "CSConfig" 1
    $top.tNo47 add $top.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text General -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo47.t0
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background gray53 -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 3 \
        -text {ColorSet on Start Up:} 
    vTcl:DefineAlias "$site_4_0.lab48" "Label1_1" vTcl:WidgetProc "CSConfig" 1
    ttk::combobox $site_4_0.tCo49 \
        -exportselection 0 -font TkTextFont -textvariable comboStartupSet \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo49" "TCombobox2" vTcl:WidgetProc "CSConfig" 1
    button $site_4_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_ConfigBtnSet -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Set 
    vTcl:DefineAlias "$site_4_0.but50" "btnSet" vTcl:WidgetProc "CSConfig" 1
    label $site_4_0.lab51 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background gray53 -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Remove ColorSet: } 
    vTcl:DefineAlias "$site_4_0.lab51" "Label2_1" vTcl:WidgetProc "CSConfig" 1
    ttk::combobox $site_4_0.tCo52 \
        -exportselection 0 -font TkTextFont -textvariable comboToDelete \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_4_0.tCo52" "TCombobox3" vTcl:WidgetProc "CSConfig" 1
    button $site_4_0.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_ConfigBtnDelete -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Delete 
    vTcl:DefineAlias "$site_4_0.but53" "btnDelete" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TFrame -background $vTcl(actual_gui_bg)
    ttk::frame $site_4_0.tFr57 \
        -borderwidth 2 -relief groove -width 445 -height 265 
    vTcl:DefineAlias "$site_4_0.tFr57" "TFrame1_1" vTcl:WidgetProc "CSConfig" 1
    set site_5_0 $site_4_0.tFr57
    label $site_5_0.lab53 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background $vTcl(actual_gui_bg) -compound left \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Samples: 
    vTcl:DefineAlias "$site_5_0.lab53" "Label3_1" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TButton -background $vTcl(actual_gui_bg)
    ttk::style configure TButton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TButton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::button $site_5_0.tBu54 \
        -takefocus {} -text Tbutton -compound left 
    vTcl:DefineAlias "$site_5_0.tBu54" "ConfTButton1" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TCheckbutton -background $vTcl(actual_gui_bg)
    ttk::style configure TCheckbutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TCheckbutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::checkbutton $site_5_0.tCh55 \
        -variable tch55 -takefocus {} -text Tcheck -compound left 
    vTcl:DefineAlias "$site_5_0.tCh55" "ConfTCheckbutton1" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TRadiobutton -background $vTcl(actual_gui_bg)
    ttk::style configure TRadiobutton -foreground $vTcl(actual_gui_fg)
    ttk::style configure TRadiobutton -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::radiobutton $site_5_0.tRa56 \
        -variable selectedButton -text TRadio -compound left 
    vTcl:DefineAlias "$site_5_0.tRa56" "ConfTRadiobutton1" vTcl:WidgetProc "CSConfig" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook $site_5_0.tNo57 \
        -width 302 -height 136 -takefocus {} 
    vTcl:DefineAlias "$site_5_0.tNo57" "ConfTNotebook1" vTcl:WidgetProc "CSConfig" 1
    frame $site_5_0.tNo57.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_5_0.tNo57.t0" "ConfTNotebook1_t1" vTcl:WidgetProc "CSConfig" 1
    $site_5_0.tNo57 add $site_5_0.tNo57.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_7_0  $site_5_0.tNo57.t0
    frame $site_5_0.tNo57.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_5_0.tNo57.t1" "ConfTNotebook1_t2" vTcl:WidgetProc "CSConfig" 1
    $site_5_0.tNo57 add $site_5_0.tNo57.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_7_1  $site_5_0.tNo57.t1
    frame $site_5_0.tNo57.t2 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$site_5_0.tNo57.t2" "ConfTNotebook1_t3" vTcl:WidgetProc "CSConfig" 1
    $site_5_0.tNo57 add $site_5_0.tNo57.t2 \
        -padding 0 -sticky nsew -state normal -text {Page 3} -image {} \
        -compound left -underline -1 
    set site_7_2  $site_5_0.tNo57.t2
    place $site_5_0.lab53 \
        -in $site_5_0 -x 20 -y 11 -width 129 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tBu54 \
        -in $site_5_0 -x 40 -y 60 -width 103 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tCh55 \
        -in $site_5_0 -x 180 -y 60 -width 94 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tRa56 \
        -in $site_5_0 -x 290 -y 60 -width 116 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tNo57 \
        -in $site_5_0 -x 50 -y 110 -width 302 -relwidth 0 -height 136 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 40 -y 80 -width 189 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tCo49 \
        -in $site_4_0 -x 235 -y 80 -width 177 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but50 \
        -in $site_4_0 -x 440 -y 70 -width 133 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 40 -y 127 -width 189 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCo52 \
        -in $site_4_0 -x 235 -y 126 -width 177 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but53 \
        -in $site_4_0 -x 440 -y 120 -width 133 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tFr57 \
        -in $site_4_0 -x 100 -y 242 -width 445 -height 265 -anchor nw \
        -bordermode ignore 
    frame $top.tNo47.t1 \
        -background gray53 -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t1" "TNotebook1_t2" vTcl:WidgetProc "CSConfig" 1
    $top.tNo47 add $top.tNo47.t1 \
        -padding 0 -sticky nsew -state normal \
        -text {Auto Foreground Computation} -image {} -compound left \
        -underline -1 
    set site_4_1  $top.tNo47.t1
    label $site_4_1.lab47 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor e \
        -background gray53 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Target Value:} 
    vTcl:DefineAlias "$site_4_1.lab47" "Label7" vTcl:WidgetProc "CSConfig" 1
    button $site_4_1.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -compound left \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Save 
    vTcl:DefineAlias "$site_4_1.but49" "Button8" vTcl:WidgetProc "CSConfig" 1
    label $site_4_1.lab50 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background gray53 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {See the following link for a discussion of this value...} 
    vTcl:DefineAlias "$site_4_1.lab50" "Label8" vTcl:WidgetProc "CSConfig" 1
    label $site_4_1.lab51 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background gray53 -compound left \
        -font {-family {DejaVu Sans} -size 12 -weight bold -slant roman -underline 1 -overstrike 0} \
        -foreground blue -highlightcolor black \
        -text https://stackoverflow.com/questions/3942878/how-to-decide-font-color-in-white-or-black-depending-on-background-color/3943023#3943023 \
        -wraplength 740 
    vTcl:DefineAlias "$site_4_1.lab51" "Label9" vTcl:WidgetProc "CSConfig" 1
    entry $site_4_1.ent47 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black \
        -textvariable AutoCompTarget -width 116 
    vTcl:DefineAlias "$site_4_1.ent47" "Entry1" vTcl:WidgetProc "CSConfig" 1
    place $site_4_1.lab47 \
        -in $site_4_1 -x 50 -y 50 -width 169 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.but49 \
        -in $site_4_1 -x 370 -y 45 -width 113 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab50 \
        -in $site_4_1 -x 200 -y 200 -width 529 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.lab51 \
        -in $site_4_1 -x 90 -y 260 -width 799 -relwidth 0 -height 81 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_1.ent47 \
        -in $site_4_1 -x 240 -y 50 -width 116 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo47.t2 \
        -background gray53 -highlightcolor black 
    vTcl:DefineAlias "$top.tNo47.t2" "TNotebook1_t3" vTcl:WidgetProc "CSConfig" 1
    $top.tNo47 add $top.tNo47.t2 \
        -padding 0 -sticky nsew -state normal -text Future -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo47.t2
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but51 \
        -in $top -x 400 -y 670 -width 203 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tNo47 \
        -in $top -x 10 -y 30 -width 942 -relwidth 0 -height 606 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top93 {base} {
    global vTcl
    if {$base == ""} {
        set base .top93
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m54" -background gray58 -highlightcolor black -padx 5 \
        -pady 5 
    wm focusmodel $top passive
    wm geometry $top 846x692+861+380
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4225 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Export"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "FormExport" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 495 -highlightcolor black -width 315 
    vTcl:DefineAlias "$top.fra47" "Frame3" vTcl:WidgetProc "FormExport" 1
    set site_3_0 $top.fra47
    vTcl::widgets::ttk::custom::CreateCmd $site_3_0.cus48 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.cus48" "Custom1" vTcl:WidgetProc "FormExport" 1
    place $site_3_0.cus48 \
        -in $site_3_0 -x 4 -y 4 -width 306 -relwidth 0 -height 486 \
        -relheight 0 -anchor nw -bordermode ignore 
    message $top.mes49 \
        -anchor nw -background gray58 -borderwidth 3 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -padx 5 \
        -pady 5 -relief groove -text Message -textvariable MessageData \
        -width 312 
    vTcl:DefineAlias "$top.mes49" "Message2" vTcl:WidgetProc "FormExport" 1
    set MessageData {Message}
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Available Colour Sets} 
    vTcl:DefineAlias "$top.lab50" "Label5" vTcl:WidgetProc "FormExport" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground #000000 -anchor w \
        -background gray58 -compound left \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {ColourSets to be Exported} 
    vTcl:DefineAlias "$top.lab51" "Label6" vTcl:WidgetProc "FormExport" 1
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -command on_ExportDismiss -compound left -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Dismiss 
    vTcl:DefineAlias "$top.but52" "btnExportDismiss" vTcl:WidgetProc "FormExport" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -command on_writeFile \
        -compound left -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Write File} 
    vTcl:DefineAlias "$top.but53" "btnWriteFile" vTcl:WidgetProc "FormExport" 1
    menu $top.m54 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 20 -y 171 -width 315 -relwidth 0 -height 495 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.mes49 \
        -in $top -x 364 -y 120 -width 312 -relwidth 0 -height 121 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 30 -y 100 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 370 -y 80 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 690 -y 20 -width 123 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 440 -y 420 -width 213 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top66 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top90 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top92 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}
set btop5 ""
if {$vTcl(borrow)} {
    set btop5 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop5 $vTcl(tops)] != -1} {
        set btop5 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop5
Window show .top93 $btop5
if {$vTcl(borrow)} {
    $btop5 configure -background plum
}

